### ISSUE TITLE
help

### ISSUE THREAD

**Issue by JVLGGames** [Athlaeos/ValhallaRaces#1]
the folder does not "unzip" when I turn on the server
I really liked your plugin, please help me!!!

**Comment by Athlaeos** [comment]
What folder??

**Comment by JVLGGames** [comment]
the valhalla folder, when I restart the server it is still in jar

Em sáb., 26 de out. de 2024, 03:27, Athlaeos ***@***.***>
escreveu:

**Comment by JVLGGames** [comment]
Can I send an image?

Em sáb., 26 de out. de 2024, 10:06, JVLG_ GamesTM ***@***.***>
escreveu:

**Comment by Athlaeos** [comment]
You're not supposed to unzip these jar files. Please look up a tutorial or how-to on how to install spigot plugins

**Comment by JVLGGames** [comment]
Yes, I know you don't need to unzip it, but how do I make the folder look
like this?



Em sáb., 26 de out. de 2024, 10:59, Athlaeos ***@***.***>
escreveu:

**Comment by JVLGGames** [comment]
Your plugin, for me, is only in the jar, I need it to be like the ones
above

Em sáb., 26 de out. de 2024, 11:10, JVLG_ GamesTM ***@***.***>
escreveu:

**Comment by JVLGGames** [comment]
I don't know how to explain it very well

Em sáb., 26 de out. de 2024, 11:11, JVLG_ GamesTM ***@***.***>
escreveu:

**Comment by Athlaeos** [comment]
I think you're trying to add images, but they're not showing. Please just join my discord server and ask me there https://discord.gg/BRGVYMeH
